### ISSUE TITLE
Call Echo on Event

### ISSUE THREAD

**Issue by sbernard31** [Ekryd/echo-maven-plugin#104]
I discover this plugin when playing with sortpom.

As an opensource library maintainer, I think it could be a useful plugin to share information to developer which try to build my project.

Thinking about that, I have the idea that it could be cool to print/echo some information on some particular event : 

Imagine you have a code formating check in your build,  
When it failed you want to print to information about how to handle this. (how to get formatter or which mvn goal to launch to format ...)

So I search if I can do that and for now I understand there is no way to do that without code : 
https://stackoverflow.com/questions/41893919/run-a-maven-plugin-when-the-build-fails

Maybe a possible feature could be to make possible to echo on given event (see https://maven.apache.org/ref/3.8.2/apidocs/org/apache/maven/execution/ExecutionEvent.html) like : 
- on build success
- on build failed
- on plugin with given artifactid failed

I share the idea just in case :slightly_smiling_face:

**Comment by Ekryd** [comment]
Hi!
This is really interesting. I don't know if this can be executed from within a normal plugin though. 
Can a plugin be both extension and plugin? Can an extension be configured with parameters?
At the moment I have to put this on the 'Great things to investigate' shelf.
I'll keep this issue open for now

**Comment by Ekryd** [comment]
Been looking into this, but it seems to be too far outside the scope of the current plugin. Sorry!

**Comment by sbernard31** [comment]
No problem, thx for looking at this :pray:
