### ISSUE TITLE
Log levels no work

### ISSUE THREAD

**Issue by delanym** [Ekryd/echo-maven-plugin#150]
Couple of things
- without specifying a log level Id expect INFO, but there's no log level prefix in the output `[INFO]`
- when I use `WARN` as mentioned at https://github.com/Ekryd/echo-maven-plugin/wiki I get a message saying `level must be either FAIL, ERROR, WARNING, INFO or DEBUG. Was: WARN`
- from a logging point of view fail and error are the same - suggest drop FAIL

**Comment by Ekryd** [comment]
1. The log used is Maven default logger. They decide how the output should be formatted. Apparently, their info level does not have a prefix.
2. I can add a WARN alias to the warning level.
3. Fail is not the same as error. ERROR is an output on a log level, but FAIL stops the whole Maven build

**Comment by delanym** [comment]
I surprised myself and found a use for FATAL. Im using the plugin to output my own help text, using -Phelp. But then I want the build to stop immediately. The output is red, but at least it doesn't course through 500 modules.
The new version works well, thank you. I have another issue which Ill log.
