### ISSUE TITLE
No echo

### ISSUE THREAD

**Issue by MarkSwanson** [Ekryd/echo-maven-plugin#7]
This echo-maven-plugin never echos anything to the console.
I've tried different phases but nothing works.
What would I have to type at the command line to see the DEBUG_BUILD message?

        <plugin>
            <groupId>com.github.ekryd.echo-maven-plugin</groupId>
            <artifactId>echo-maven-plugin</artifactId>
            <version>1.2.0</version>
            <inherited>false</inherited>
            <executions>
                <execution>
                    <id>someId</id>
                    <phase>clean</phase>
                    <goals>
                        <goal>echo</goal>
                    </goals>
                    <configuration>
                        <message>DEBUG_BUILD: a</message>
                    </configuration>
                </execution>
            </executions>
        </plugin>

**Comment by Ekryd** [comment]
Hi, Sounds strange. I will have to look into this.

**Comment by Ekryd** [comment]
I put the plugin configuration under plugins in the pom-file and executed 'mvn clean'.
Output was:
```
[INFO] ----------------------< mine:xxx >----------------------
[INFO] Building xxx 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ xxx ---
[INFO] Deleting /Workspace/xxx/target
[INFO]
[INFO] --- echo-maven-plugin:1.2.0:echo (someId) @ xxx ---
[INFO] DEBUG_BUILD: a
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.279 s
[INFO] Finished at: 2020-09-21T22:07:55+02:00
[INFO] ------------------------------------------------------------------------
```

Seems to work fine
